import { BarChart3, PieChart as PieIcon, Store, WalletCards } from 'lucide-react';
import { Bar, BarChart, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { money } from './ledgerStats';
interface Props { stats: ReturnType<typeof import('./ledgerStats').buildStats>; }
const colors = ['#76506f','#7c9670','#cf9b67','#7494a4','#b87a72','#8b7d59','#7e87ad','#a2779d'];
const shortMoney = (value: number) => `¥${Math.round(value)}`;
function Ranking({ title, icon: Icon, data }: { title: string; icon: typeof Store; data: { name: string; amount: number }[] }) {
  return <section className="rounded-3xl border border-white/80 bg-white/75 p-4 shadow-[0_12px_28px_rgba(91,72,72,0.08)]"><h2 className="flex items-center gap-2 font-black text-[#403632]"><Icon size={17} className="text-[#76506f]" />{title}</h2><div className="mt-3 space-y-2">{data.length ? data.map((item, index) => <div key={`${item.name}-${index}`} className="flex items-center gap-2"><span className="w-5 text-xs font-black text-[#af9691]">{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm font-bold text-[#5f4d49]">{item.name}</span><span className="text-sm font-black text-[#76506f]">{money(item.amount)}</span></div>) : <p className="py-4 text-center text-sm font-bold text-[#9a817e]">暂无支出数据</p>}</div></section>;
}
export function LedgerCharts({ stats }: Props) {
  const tooltip = { contentStyle: { borderRadius: 14, border: '1px solid rgba(112,85,101,.12)', background: '#fffdf9' }, formatter: (value: number | string | undefined) => money(Number(value ?? 0)) };
  return <>
    <section className="grid gap-3 lg:grid-cols-2"><article className="rounded-3xl border border-white/80 bg-white/75 p-4 shadow-[0_12px_28px_rgba(91,72,72,0.08)]"><h2 className="flex items-center gap-2 font-black text-[#403632]"><BarChart3 size={17} className="text-[#76506f]" />月度支出趋势</h2><div className="mt-4 h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={stats.monthly}><XAxis dataKey="name" tick={{ fontSize: 10, fill: '#9a817e' }} /><YAxis tickFormatter={shortMoney} tick={{ fontSize: 10, fill: '#9a817e' }} width={46} /><Tooltip {...tooltip} /><Bar dataKey="amount" fill="#76506f" radius={[7, 7, 0, 0]} /></BarChart></ResponsiveContainer></div></article><article className="rounded-3xl border border-white/80 bg-white/75 p-4 shadow-[0_12px_28px_rgba(91,72,72,0.08)]"><h2 className="flex items-center gap-2 font-black text-[#403632]"><BarChart3 size={17} className="text-[#7c9670]" />最近 30 天支出</h2><div className="mt-4 h-56"><ResponsiveContainer width="100%" height="100%"><LineChart data={stats.daily}><XAxis dataKey="name" minTickGap={26} tick={{ fontSize: 10, fill: '#9a817e' }} /><YAxis tickFormatter={shortMoney} tick={{ fontSize: 10, fill: '#9a817e' }} width={46} /><Tooltip {...tooltip} /><Line type="monotone" dataKey="amount" stroke="#7c9670" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></div></article></section>
    <section className="grid gap-3 lg:grid-cols-2"><article className="rounded-3xl border border-white/80 bg-white/75 p-4 shadow-[0_12px_28px_rgba(91,72,72,0.08)]"><h2 className="flex items-center gap-2 font-black text-[#403632]"><PieIcon size={17} className="text-[#a87743]" />分类占比</h2><div className="mt-3 h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={stats.categories} dataKey="amount" nameKey="name" innerRadius={52} outerRadius={82} paddingAngle={2}>{stats.categories.map((entry, index) => <Cell key={entry.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip {...tooltip} /><Legend wrapperStyle={{ fontSize: 11 }} /></PieChart></ResponsiveContainer></div></article><Ranking title="分类金额排行" icon={PieIcon} data={stats.categories} /></section>
    <section className="grid gap-3 lg:grid-cols-3"><Ranking title="商户 Top 10" icon={Store} data={stats.merchants} /><Ranking title="账户排行" icon={WalletCards} data={stats.accounts} /><Ranking title="支付方式排行" icon={WalletCards} data={stats.payMethods} /></section>
  </>;
}
