import { AlertTriangle, CheckCircle2, ChevronDown, ShieldAlert } from 'lucide-react';
import { useState } from 'react';
import type { QualityItem } from './ledgerTypes';
import { displayValue } from './ledgerStats';
export function LedgerQualityPanel({ items }: { items: QualityItem[] }) {
  const [open, setOpen] = useState<string | null>(null);
  const total = (item: QualityItem) => item.count ?? item.records.length;
  const critical = items.filter(item => item.severity === 'critical' && total(item)).length;
  const notices = items.filter(item => item.severity === 'notice' && total(item)).length;
  return <section className="rounded-[28px] border border-white/80 bg-white/75 p-4 shadow-[0_16px_36px_rgba(91,72,72,0.1)]"><div className="flex items-start gap-3"><div className={`grid h-11 w-11 place-items-center rounded-2xl ${critical ? 'bg-[#fff0ee] text-[#bd564b]' : notices ? 'bg-[#fff6e7] text-[#b47a2b]' : 'bg-[#eaf4e8] text-[#5c8a55]'}`}>{critical ? <ShieldAlert size={21} /> : notices ? <AlertTriangle size={21} /> : <CheckCircle2 size={21} />}</div><div><h2 className="font-black text-[#403632]">数据质量检查</h2><p className="mt-1 text-xs font-bold leading-5 text-[#8b7471]">{critical ? `${critical} 项高优先级异常，请先核对。` : notices ? `${notices} 项待确认，不影响看板统计。` : '未发现异常，账本状态良好。'}</p></div></div><div className="mt-4 space-y-2">{items.map(item => { const count = total(item); const opened = open === item.key; const color = item.severity === 'critical' ? 'text-[#bd564b] bg-[#fff1ef]' : 'text-[#a4772c] bg-[#fff7e9]'; return <div key={item.key} className="overflow-hidden rounded-2xl bg-[#f8f4f1]"><button type="button" onClick={() => count && setOpen(opened ? null : item.key)} className="flex w-full items-center gap-3 px-3 py-3 text-left"><span className={`rounded-full px-2 py-1 text-xs font-black ${count ? color : 'bg-[#edf3ea] text-[#65805e]'}`}>{count ? `${count} 条` : '正常'}</span><span className="min-w-0 flex-1 text-sm font-black text-[#5f4d49]">{item.title}</span>{count > 0 && <ChevronDown size={16} className={`text-[#9a817e] transition ${opened ? 'rotate-180' : ''}`} />}</button>{opened && <div className="border-t border-[#eadfda] px-3 py-3"><p className="text-xs font-bold text-[#9a817e]">{item.description}</p><div className="mt-2 space-y-2">{item.records.slice(0, 8).map(record => <div key={`${item.key}-${record.sourceRow}`} className="rounded-xl bg-white/70 px-3 py-2 text-xs font-bold text-[#715d58]">第 {record.sourceRow} 行 · {record.date || '-'} · {displayValue(record.merchant)} · {record.amountValid ? `¥${record.amount.toFixed(2)}` : `金额 ${record.amountRaw || '-'}`}<span className="mt-1 block break-all text-[#9a817e]">原始行：{record.rawRow || '-'}</span></div>)}{count > 8 && <p className="text-xs font-bold text-[#9a817e]">仅展示前 8 条，共 {count} 条。</p>}{!item.records.length && <p className="mt-2 text-xs font-bold text-[#bd564b]">请重新导入并检查 CSV 表头与分隔符。</p>}</div></div>}</div>; })}</div></section>;
}
